# Generated by Django 5.0.6 on 2024-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_address_alter_item_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
