# Generated by Django 5.0.6 on 2024-07-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_item_address_alter_item_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='phone',
        ),
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='agency_employee',
            field=models.EmailField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='blood_type',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='civil_status',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='date_of_birth',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fathers_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gsis_id_no',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height_m',
            field=models.EmailField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mothers_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='occupation',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pagibig_id_no',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='philhealth_no',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone_no',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='province',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='religion',
            field=models.EmailField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_address',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sss_no',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='telephone_no',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tin_no',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_kg',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='zip_code',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
