# Generated by Django 5.0.6 on 2024-07-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_item_phone_item_age_item_agency_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
