# Generated by Django 5.0.6 on 2024-07-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='item',
            name='agency_employee',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='height_m',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='religion',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
